apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: modules/service-one
    cyclops-ui.com/write-repo: https://github.com/petar-cvit/demo-chart-releases
    cyclops-ui.com/write-revision: main
    cyclops/reconciled-at: "2025-03-23T23:20:39+01:00"
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: service-one
  name: alpha
spec:
  targetNamespace: default
  template:
    path: app-template
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    general:
      environment:
        ENVIRONMENT: production
      image: nginx
      version: 1.14.2
    networking:
      expose: true
      port: 80
      type: ClusterIP
    scaling:
      replicas: 5
status: {}
