apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: modules/product-one
    cyclops-ui.com/write-repo: https://github.com/petar-cvit/demo-chart-releases
    cyclops-ui.com/write-revision: main
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: product-one
  name: delta
spec:
  targetNamespace: default
  template:
    path: product-one
    repo: https://github.com/petar-cvit/demo-chart-releases
    sourceType: git
    version: main
  values:
    general:
      environment:
        ENVIRONMENT: production
    networking:
      expose: true
      port: 80
      type: ClusterIP
    scaling:
      replicas: 5
status: {}
