apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-one
  namespace: argocd
spec:
  destination:
    namespace: cyclops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: modules/service-one
    repoURL: https://github.com/petar-cvit/demo-chart-releases
    targetRevision: main
