{{- if ((.Values.networking).expose) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-product-one
  labels:
    product: product-one
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.networking.type | default "ClusterIP" }}
  ports:
    - port: {{ (.Values.networking).port }}
      targetPort: {{ (.Values.networking).port }}
      protocol: TCP
      name: http
  selector:
    product: product-one
    app: {{ .Release.Name }}
  {{- end }}
