apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: modules/product-two
    cyclops-ui.com/write-repo: https://github.com/KaradzaJuraj/demo-chart-releases
    cyclops-ui.com/write-revision: main
  creationTimestamp: null
  name: drug
spec:
  targetNamespace: default
  template:
    path: product-two
    repo: https://github.com/KaradzaJuraj/demo-chart-releases
    sourceType: git
    version: main
  values:
    general:
      environment:
        ENVIRONMENT: production
    networking:
      expose: true
      port: 80
      type: ClusterIP
    scaling:
      replicas: 1
status: {}
